
services:

  app:
    build:
      context: ./docker/php-fpm  
    image: laravel-online-shop
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/API
    environment:
      - APP_ENV=prod
    expose:
      - 9000
    depends_on:
      - db


  web:
    image: nginx:1.26.0-alpine
    container_name: nginx_webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/API
      - ./nginx.conf:/etc/nginx/nginx.conf
     

    ports:
      - '8084:80'
    depends_on:
      -  app


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8083:80
    # volumes: 
    # - ./:/var/www/API


# pour stocker les resultats des requetes frequentes ou les sessions, je l'utilise pour les files d'attentes
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'


  db:
    image: mysql
    container_name: mysql-database
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: onlineShop_laraveldb

    ports:
      - '3308:3306'
    volumes:
      # - ./db_data:/var/lib/mysql
      -  db_data:/var/lib/mysql

volumes:
  db_data:


